### ISSUE TITLE
nesting more than one key deep

### ISSUE THREAD

**Issue by FerretCode** [FerretCode/my-dog-likes-cheese#2]
at the moment i'm not adding features to this repository every day, so i still haven't been able to add multi-key nesting. i'm interested on hearing your guys' feedback on how you think this should be implemented.

at the moment when supplying a nestedkey argument it can only go one key past the specified key argument. i'm thinking maybe an array destructor that can be applied to an arbitrary number of keys. for example, an argument could go like:

`...['key 1', 'key 2']`

looking forward to hearing feedback.

**Comment by Avngarde** [comment]
I think we can just use an array for nested keys, and in the foreach add key to the previous key

**Comment by FerretCode** [comment]
that could work, i'll do some testing

**Comment by FerretCode** [comment]
fixed it
